function greeting () {
  return 'atomic habit new book '
}

console.log(greeting())

// --TRADIONAL FUNCTION
// -- FUNCTION AS VARIBLE
//-- ARROW OPERATOR -- FAT ARROW FUCTION
// --- CALLBACK FUCNTION
// -- ANONYMOUS FUNCTION
//-- IFFE --> SELF  EXECUTING ANONYMOUS FUNCTION ----> EACH NODE CORE OF 5 ARGUMENT OR IMPORT , EXPORT LOGIC
